### ISSUE TITLE
Does not build?

### ISSUE THREAD

**Issue by pcercuei** [flathub/net.pioneerspacesim.Pioneer#1] opened 2018-08-27 13:39 UTC
https://flathub.org/apps/details/net.pioneerspacesim.Pioneer is 404.

Is there a problem with the JSON? Or is there something that has to be done manually to get it listed on Flathub?

**Comment by nedrichards** [comment] 2018-08-30 14:27
I've triggered a rebuild manually and it seems to be failing JSON validation: https://flathub.org/builds/#/builders/53/builds/1827

**Comment by nedrichards** [comment] 2018-08-30 14:28
I've pushed a commit that removes that errant comma https://github.com/flathub/net.pioneerspacesim.Pioneer/commit/117390a1935de88f28b8c26e4c761182a39d8794

**Comment by nedrichards** [comment] 2018-08-30 14:31
Here's the state of the build: https://flathub.org/builds/#/builders/2/builds/4061

**Comment by nedrichards** [comment] 2018-08-30 15:14
Pushed a fix to the release tag which caused the build to fail validation https://github.com/flathub/net.pioneerspacesim.Pioneer/commit/e332eb10c3adc438f1855ecf4a585129518de54b

**Comment by nedrichards** [comment] 2018-08-30 15:41
Icon locations failing https://flathub.org/builds/#/builders/36/builds/352 will investigate further

**Comment by nedrichards** [comment] 2018-09-18 11:57
https://github.com/flathub/net.pioneerspacesim.Pioneer/commit/2d1581d4f531b5a912647e579c820a3dae1c2d98 doesn't fix this, but does move to a much more regular JSON layout for flathub. I expect this build to fail: https://flathub.org/builds/#/builders/2/builds/4588 with:

```
Running appstream-compose
Processing application net.pioneerspacesim.Pioneer
Error loading desktop file: Failed to find icon: Failed to find icon net.pioneerspacesim.Pioneer
Error: ERROR: appstream-compose failed: Child process exited with code 1
```
@TingPing @barthalion do you have any idea what's going on here? This has me genuinely stumped. I've tried the obvious debugging things so all that I can think is left is something really stupid that I've missed.

**Comment by pcercuei** [comment] 2018-09-18 12:33
IIRC last time I fixed it (or worked around, your choice) by removing the .desktop extension in the <launchable> field in the appstream file. Then somebody changed it back :)

**Comment by nedrichards** [comment] 2018-09-19 09:19
@pcercuei that change 'works' by not actually finding and building the appdata correctly, which means it'd fail in the flathub build system that requires that and the app wouldn't be visible in software stores or the flathub website - just from the flatpak command line.

**Comment by pcercuei** [comment] 2018-09-19 14:09
Alright, makes sense.

**Comment by TingPing** [comment] 2018-09-19 16:44
I don't get it either, it must be an `appstream` bug.

**Comment by nedrichards** [comment] 2018-09-20 17:39
OK @hughsie is there anything we can do to help this be more reproducible other than 'check this out and try and build the flatpak'?

**Comment by hughsie** [comment] 2018-09-20 18:06
Is there a filelist somewhere?

**Comment by nedrichards** [comment] 2018-09-20 18:36
Build logs are here: https://flathub.org/builds/#/builders/2/builds/4611 I'm not sure if there's a way of getting access to the files to share @ramcq I know you were looking at this once upon a time.

**Comment by TingPing** [comment] 2018-09-20 19:56
> Is there a filelist somewhere?

```
share
├── appdata
│   └── net.pioneerspacesim.Pioneer.appdata.xml
├── applications
│   └── net.pioneerspacesim.Pioneer.desktop
└── icons
    └── hicolor
        ├── 128x128
        │   └── apps
        │       └── net.pioneerspacesim.Pioneer.png
        ├── 16x16
        │   └── apps
        │       └── net.pioneerspacesim.Pioneer.png
        ├── 22x22
        │   └── apps
        │       └── net.pioneerspacesim.Pioneer.png
        ├── 24x24
        │   └── apps
        │       └── net.pioneerspacesim.Pioneer.png
        ├── 256x256
        │   └── apps
        │       └── net.pioneerspacesim.Pioneer.png
        ├── 32x32
        │   └── apps
        │       └── net.pioneerspacesim.Pioneer.png
        ├── 40x40
        │   └── apps
        │       └── net.pioneerspacesim.Pioneer.png
        ├── 48x48
        │   └── apps
        │       └── net.pioneerspacesim.Pioneer.png
        └── 64x64
            └── apps
                └── net.pioneerspacesim.Pioneer.png
```

Icons are valid pngs.
Desktop file has right icon name: https://github.com/flathub/net.pioneerspacesim.Pioneer/blob/master/pioneer.desktop#L7
Appdata has right desktop-id: https://github.com/flathub/net.pioneerspacesim.Pioneer/blob/master/pioneer.appdata.xml#L10

**Comment by hughsie** [comment] 2018-09-20 20:04
Hmm, that looks fine. Will debug tomorrow.

**Comment by hughsie** [comment] 2018-09-20 20:29
Hmm, running this `appstream-compose --prefix . net.pioneerspacesim.Pioneer` locally in `build-dir/files` succeeds. I wonder if building against the GNOME 3.28 Sdk might bring in a newer appstream-compose that works?

**Comment by TingPing** [comment] 2018-09-20 21:20
> Hmm, running this `appstream-compose --prefix . net.pioneerspacesim.Pioneer` locally in `build-dir/files` succeeds.

It fails on my host with `appstream-utils` version `0.7.12`.

**Comment by nedrichards** [comment] 2018-11-16 13:32
So this issue seems to be https://github.com/hughsie/appstream-glib/issues/271 I've put in a workaround with https://github.com/flathub/net.pioneerspacesim.Pioneer/commit/4d5967ebf31c4e563e5f9ebcac7d14334f32f2a2 but we probably want to make it not build in /app/usr/ instead.

**Closed by nedrichards** 2018-11-16 13:32 UTC
